/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.84
 * Generated at: 2023-01-12 19:09:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registration_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/normal_navbar.jsp", Long.valueOf(1673027180822L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Registration</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"css/styles.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark pp\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\"><span class=\"fa fa-american-sign-language-interpreting\"></span>Tech-Blog</a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"index.jsp\"><span class=\"fa fa-home\"></span>Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\"><span class=\"fa fa-external-link\"></span>Link</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("          Categories\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Programming</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Computer Network</a>\r\n");
      out.write("          <div class=\"dropdown-divider\"></div>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"#\">Sports</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link disabled\" href=\"#\"><span class=\"fa fa-paper-plane-o\"></span>Contact</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link disabled\" href=\"login_page.jsp\"><span class=\"fa fa-paper-plane-o\"></span>Login</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link disabled\" href=\"registration_page.jsp\"><span class=\"fa fa-paper-plane-o\"></span>SignUp</a>\r\n");
      out.write("      </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <form class=\"form-inline my-2 my-lg-0\">\r\n");
      out.write("      <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\r\n");
      out.write("      <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\"><span class=\"fa fa-search\"></span></button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>");
      out.write("\r\n");
      out.write("	<main class=\"d-flex align-items-center pp\" style=\"height: 100vh\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("				<div class=\"card\">\r\n");
      out.write("					<div class=\"card-header text-center pp text-white\">\r\n");
      out.write("						<span class=\"fa fa-user-plus\"></span><br> Register Here\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<form id=\"reg-form\" action=\"RegisterServlet\" method=\"POST\">\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"username\">UserName</label> <input name=\"user_name\"\r\n");
      out.write("									required type=\"text\" class=\"form-control\" id=\"user_name\"\r\n");
      out.write("									aria-describedby=\"emailHelp\" placeholder=\"Enter name\">\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"exampleInputEmail1\">Email address</label> <input\r\n");
      out.write("									name=\"user_email\" required type=\"email\" class=\"form-control\"\r\n");
      out.write("									id=\"exampleInputEmail1\" aria-describedby=\"emailHelp\"\r\n");
      out.write("									placeholder=\"Enter email\"> <small id=\"emailHelp\"\r\n");
      out.write("									class=\"form-text text-muted\">We'll never share your\r\n");
      out.write("									email with anyone else.</small>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"exampleInputPassword1\">Password</label> <input\r\n");
      out.write("									name=\"user_password\" required type=\"password\" class=\"form-control\"\r\n");
      out.write("									id=\"exampleInputPassword1\" placeholder=\"Password\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"gender\">Gender</label><br> <input required type=\"radio\"\r\n");
      out.write("									id=\"gender\" name=\"gender\" value=\"male\">Male <input\r\n");
      out.write("									required type=\"radio\" id=\"gender\" name=\"gender\" value=\"female\">Female\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\"></div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-check\">\r\n");
      out.write("								<input name=\"check\" type=\"checkbox\" class=\"form-check-input\"\r\n");
      out.write("									id=\"exampleCheck1\"> <label class=\"form-check-label\"\r\n");
      out.write("									for=\"exampleCheck1\">Terms And Condition</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<br>\r\n");
      out.write("							<div class=\"container text-center\" id=\"loader\"\r\n");
      out.write("								style=\"display: none\">\r\n");
      out.write("								<span class=\"fa fa-refresh fa-spin fa-4x\"></span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<br>\r\n");
      out.write("							<button id=\"submit-btn\" type=\"submit\" class=\"btn btn-primary\">Submit</button>\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("            src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("            integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("        crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"js/js.js\" type=\"text/javascript\"></script>\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.2/sweetalert.min.js\" integrity=\"sha512-AA1Bzp5Q0K1KanKKmvN/4d3IRKVlv9PYgwFPvm32nPO6QS8yH1HO7LbgB1pgiOxPtfeg5zEn2ba64MUcqJx6CA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("            $(document).ready(function () {\r\n");
      out.write("                console.log(\"loaded........\")\r\n");
      out.write("                $('#reg-form').on('submit', function (event) {\r\n");
      out.write("                    event.preventDefault();\r\n");
      out.write("                    let form = new FormData(this);\r\n");
      out.write("                    $(\"#submit-btn\").hide();\r\n");
      out.write("                    $(\"#loader\").show();\r\n");
      out.write("                    //send register servlet:\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                        url: \"RegisterServlet\",\r\n");
      out.write("                        type: 'POST',\r\n");
      out.write("                        data: form,\r\n");
      out.write("                        success: function (data, textStatus, jqXHR) {\r\n");
      out.write("                            console.log(data)\r\n");
      out.write("                            $(\"#submit-btn\").show();\r\n");
      out.write("                            $(\"#loader\").hide();\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                            if(data.trim()==='Done'){\r\n");
      out.write("                            	swal(\"Register Successfull...Redirecting Login page\")\r\n");
      out.write("                            .then((value) => {\r\n");
      out.write("                              window.location=\"login_page.jsp\"\r\n");
      out.write("                            });\r\n");
      out.write("                            }else{\r\n");
      out.write("                                swal(data);\r\n");
      out.write("\r\n");
      out.write("                            }\r\n");
      out.write("                            \r\n");
      out.write("                            \r\n");
      out.write("                        },\r\n");
      out.write("                        error: function (jqXHR, textStatus, errorThrown) {\r\n");
      out.write("                        	 $(\"#submit-btn\").show();\r\n");
      out.write("                             $(\"#loader\").hide();\r\n");
      out.write("                            swal(\"something went wrong..try again\");\r\n");
      out.write("                        },\r\n");
      out.write("                        processData: false,\r\n");
      out.write("                        contentType: false\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
